name: Comment on PR based on labels
on:
  pull_request_target:
    types: [ labeled ]
    branches:
      - master
      - main
jobs:
  add-pr-comment:
  runs-on: ubuntu-latest
    steps:
      - name: Add PR Comment
        uses: oleksiyrudenko/gha-pr-comment-per-label@dev
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          labels: '["bug","question"]'
